brew "zsh"
brew "curl"
brew "composer"
brew "vim"
brew "git"
brew "gnupg"
brew "wget"
brew "pinentry-mac"
brew "tmux"
brew "lftp"

cask_args appdir: "~/Applications", require_sha: true

cask "alfred"
cask "coconutBattery"
cask "docker"
cask "flux"
cask "firefox"
cask "insomnia"
cask "iterm2"
cask "lulu"
cask "marta"
cask "sequel-ace"
cask "sublime-text"
cask "the-unarchiver"
cask "thunderbird"
cask "vlc"
